### ISSUE TITLE
LogManager properties file based configuration support

### ISSUE THREAD

**Issue by kortemik** [teragrep/jla_04#5]
Feature request: LogManager properties file based configuration support

**Comment by kortemik** [comment]
https://stackoverflow.com/questions/10532291/how-to-configure-the-properties-of-a-specific-filehandler
https://stackoverflow.com/questions/3639694/java-util-logging-properties-how-to-log-to-two-different-files
https://docs.oracle.com/javase/8/docs/api/java/util/logging/LogManager.html

**Comment by StrongestNumber9** [comment]
Fixed in 1.5.0
