### ISSUE TITLE
Support for log event formatting

### ISSUE THREAD

**Issue by kortemik** [teragrep/jla_04#6]
LogRecord is to be rendered with a Formatter defined in configuration properties. Instead of using the logRecord.getMessage() directly as in https://github.com/teragrep/jla_04/blob/master/src/main/java/com/teragrep/jla_04/RelpHandler.java#L80

Example use case
https://www.logicbig.com/tutorials/core-java-tutorial/logging/customizing-default-format.html

**Comment by kortemik** [comment]
Following may become handy

https://github.com/openjdk/jdk/blob/739769c8fc4b496f08a92225a12d07414537b6c0/src/java.logging/share/classes/java/util/logging/FileHandler.java

**Comment by StrongestNumber9** [comment]
Implemented in commit 9874583c3460fe523c8ab86ab292f457d5f0f9b4
