### ISSUE TITLE
change system properties to use com.teragrep.jla_04 prefix instead of java.util.logging

### ISSUE THREAD

**Issue by kortemik** [teragrep/jla_04#8]
change system properties to use com.teragrep.jla_04 prefix instead of java.util.logging.

using java.util.logging prefix may cause undesired results such as collision with java.util.logging package properties as seen in some configurations which enter a configuration loop.

**Comment by kortemik** [comment]
upgrade major version as bc break.

**Comment by StrongestNumber9** [comment]
Implemented in 1.5.0
